version: '3.4'

services:
  django:
    build: backend
    entrypoint: ./entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app:cached
    depends_on:
      - db
    env_file:
      - .env

  frontend:
      build: frontend
      user: ${DOCKER_USER}
      volumes:
          - ./frontend:/app:cached
      env_file:
          - .env

  nginx:
      image: nginx:1.19.3
      volumes:
          - ./app/nginx.conf:/etc/nginx/templates/default.conf.template
          - ./frontend/build:/usr/share/nginx/html/
      restart: unless-stopped
      depends_on:
          - django
          - frontend
      env_file:
          - .env
      ports:
        - "80:80"
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.spectr.rule=Host(`spectr.dev.andyi95.com`)"
          - "traefik.http.services.spectr.loadbalancer.server.port=80"

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - ./db-data:/data
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"

